version: "3.9"
services:
    web:
        build: .
        ports:
            - "8001:80"
        depends_on:
           - db
    db:
        image: mcr.microsoft.com/mssql/server
        user: '0:0'
        container_name: sqlserver2019
        ports:
          - 1433:1433
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: PasswordO1.
          MSSQL_PID: Express